/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_utils_DnsUtils_Companion */

#ifndef _Included_com_example_myapplication_utils_DnsUtils_Companion
#define _Included_com_example_myapplication_utils_DnsUtils_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_utils_DnsUtils_Companion
 * Method:    getIps
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_myapplication_utils_DnsUtils_00024Companion_getIps
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
