/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_speech_micro_Hello */

#ifndef _Included_com_google_speech_micro_GoogleHotwordData
#define _Included_com_google_speech_micro_GoogleHotwordData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_speech_micro_GoogleHotwordData
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_speech_micro_GoogleHotwordData_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_speech_micro_GoogleHotwordData
 * Method:    nativeGetHotwordModelId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_google_speech_micro_GoogleHotwordData_nativeGetHotwordModelId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_speech_micro_GoogleHotwordData
 * Method:    nativeIdealBufferBytes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_google_speech_micro_GoogleHotwordData_nativeIdealBufferBytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_speech_micro_GoogleHotwordData
 * Method:    nativeIsSpeakerModelCompatible
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_speech_micro_GoogleHotwordData_nativeIsSpeakerModelCompatible
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_google_speech_micro_GoogleHotwordData
 * Method:    nativeIsSpeakerVerificationEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_speech_micro_GoogleHotwordData_nativeIsSpeakerVerificationEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_speech_micro_GoogleHotwordData
 * Method:    nativeMaxNumImpostorAttemptsForVoiceUnlock
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_google_speech_micro_GoogleHotwordData_nativeMaxNumImpostorAttemptsForVoiceUnlock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_speech_micro_GoogleHotwordData
 * Method:    nativeNew
 * Signature: ([BIIIZ)J
 */
JNIEXPORT jlong JNICALL Java_com_google_speech_micro_GoogleHotwordData_nativeNew
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
