/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_speech_recognizer_AbstractRecognizer */

#ifndef _Included_com_google_speech_recognizer_AbstractRecognizer
#define _Included_com_google_speech_recognizer_AbstractRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_speech_recognizer_AbstractRecognizer
 * Method:    nativeCancel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_google_speech_recognizer_AbstractRecognizer_nativeCancel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_google_speech_recognizer_AbstractRecognizer
 * Method:    nativeConstruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_google_speech_recognizer_AbstractRecognizer_nativeConstruct
  (JNIEnv *, jobject);

/*
 * Class:     com_google_speech_recognizer_AbstractRecognizer
 * Method:    nativeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_speech_recognizer_AbstractRecognizer_nativeDelete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_google_speech_recognizer_AbstractRecognizer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_speech_recognizer_AbstractRecognizer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_google_speech_recognizer_AbstractRecognizer
 * Method:    nativeInitFromProto
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_com_google_speech_recognizer_AbstractRecognizer_nativeInitFromProto
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     com_google_speech_recognizer_AbstractRecognizer
 * Method:    nativeRun
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_speech_recognizer_AbstractRecognizer_nativeRun
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
